
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'timbertraces_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  timbertraces_dbt:
    # persist resource descriptions as column and relation comments in the database
    # https://docs.getdbt.com/reference/resource-configs/persist_docs
    +persist_docs:
      relation: true
      columns: true

    # materialize marts and analytics models as tables and staging as views by default unless otherwise specified.
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
    reports:
      +schema: reports
      +materialized: table

  # Configuring models from Fivetran's packages
  shopify_source:
    +schema: staging
  shopify:
    +schema: staging

  google_ads_source:
    +schema: staging
  google_ads:
    +schema: staging 

vars:  
  # Configuring variables for Fivetran's packages
  shopify_database: fivetran-sources
  shopify_schema: shopify
  
  google_ads_database: fivetran-sources
  google_ads_schema: google_ads  
